---
title: "Pogen Analytics"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(shiny)
library(arules)
library(arulesViz)
library(RColorBrewer)
library(dplyr, warn.conflicts = F)
library(lubridate, warn.conflicts = F)
library(knitr, warn.conflicts = F)
library(kableExtra)
library(ggpubr)
library(ggplot2)
library(plyr)
library(DT)
library(tidyverse)
library(readxl)
library(plotly)
knitr::opts_chunk$set(echo = TRUE)
opts_knit$set(root.dir = "/home/larissa/Escritorio/git/")

data <- read.csv(file = "data_supermercado.csv")
data <- select(.data = data, BASKET_ID, COMMODITY_DESC)
names(data) <- c("ticket","items")

```


## Market Basket Analysis {.tabset .tabset-fade .tabset-pills}

<br />

El Market Basket Analysis, es utilizado en la industria del retail e e-commerce para entender el comportamiento de compra de los clientes. Esta metodología detecta las combinaciones de artículos que suelen comprar al mismo tipo. 

Pogen Analytics pone a tu disposición 3 demos para que conozcas nuestra plataforma de Market Basket Análysis y los beneficios que puede traer a tu negocio:

* Demo Supermercado
* Demo Zapatería
* Demo Tienda Departamental

A través de los diferentes demos podrás analisar su Market Basket Análysis y las recomendaciones que Pogen Analytics suguiere para resolver cada uno de sus casos.

<br />

### Supermercado {.tabset .tabset-fade}

La compra de productos de supermercado online alrededor del mundo ya es una tendencia, en México es el que tiene mayor frecuencia de compra semanal con el 23% entre todas las categorías de compra en línea. 

Debido a la importancia que va cobrando la compra del súper vía online, Supermercado Intermarche busca ofrecer a sus clientes una mejor experiencia de compra ofreciendo una sección de paquetes de productos que sus clientes suelen comprar.

#### Recomendaciones 

Agregar recomendaciones*

#### Análisis de ventas 

Agregar Analisis de ventas

#### Market Basket Analysis 

Agregar Market Basket

#### Itemsets 

Agregar Itemsets

#### Reglas de Asociación 

Agregar Reglas

### Zapatería  {.tabset .tabset-fade}

Zapatería busca conocer el mejor acomodo de sus modelos. Además de promociones para su seccion de accesorios.

#### Recomendaciones 

Agregar recomendaciones*

#### Análisis de ventas 

Agregar Analisis de ventas

#### Market Basket Analysis 

Agregar Market Basket

#### Itemsets 

Agregar Itemsets

#### Reglas de Asociación 

Agregar Reglas

### Tienda Departamental  {.tabset .tabset-fade}

Tienda departamental busca hacer el layout optimo de su tienda. 

#### Recomendaciones 

Agregar recomendaciones*

#### Análisis de ventas 

Agregar Analisis de ventas

#### Market Basket Analysis 

Agregar Market Basket

#### Itemsets 

Agregar Itemsets

#### Reglas de Asociación 

Agregar Reglas

